# Generated by Django 4.1.13 on 2023-11-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseMuscleGroup',
        ),
    ]
