# Generated by Django 4.1.13 on 2023-11-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trainingplan_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musclegroup',
            old_name='muscle_group_name',
            new_name='muscle_group',
        ),
    ]
